### ISSUE TITLE
Last Week in Pony - July 15, 2018

### ISSUE THREAD

**Issue by jdhorwitz** [ponylang/ponylang.github.io#312] opened 2018-07-08 19:11 UTC

**Comment by SeanTAllen** [comment] 2018-07-11 19:53
A new beginner friendly issue has landed for the Pony compiler? Want to give it a shot:

https://github.com/ponylang/ponyc/issues/2821

**Comment by SeanTAllen** [comment] 2018-07-11 20:07
Due to confusion caused by its name, we are going to rename our little package manager pony-stable to a new name. 

Got a name to nominate? Want to vote on options? Chime in on the issue:

https://github.com/ponylang/pony-stable/issues/75

**Comment by SeanTAllen** [comment] 2018-07-11 20:20
Audio from the July 11th Pony Development Sync call is now available:

https://pony.groups.io/g/dev/files/Pony%20Sync/2018_07_11

**Comment by SeanTAllen** [comment] 2018-07-12 12:16
New beginner friendly issue with our little dependency manager that could "pony-stable". Interested in contributing? We have a flakey integration test, could you be the person to fix it? We think you could be:

https://github.com/ponylang/pony-stable/issues/76

**Comment by aturley** [comment] 2018-07-13 02:49
I've been working on material for a Pony workshop that I've been giving (and will present at ICFP in September). It is now in a state where I think it is useful, and I'd love to get feedback on it.

https://github.com/aturley/pony-workshop

**Comment by SeanTAllen** [comment] 2018-07-14 22:39
Apparently Brian Callahan has Pony working on OpenBSD. Here's to hoping he opens a PR at some point.

https://twitter.com/__briancallahan/status/1018263079816134657

**Closed** 2018-07-15 18:13 UTC
